[package]
name = "frida-gum"
version = "0.1.1"
authors = ["meme <keegan@sdf.org>"]
edition = "2018"
license = "wxWindows"
repository = "https://github.com/meme/frida-rust"
description = "Rust bindings for Frida Gum"

[features]
event-sink = ["frida-gum-sys/event-sink"]
invocation-listener = ["frida-gum-sys/invocation-listener"]

[dependencies]
frida-gum-sys = { path = "../frida-gum-sys", version = "0.1.1" }
num = "0.3.1"
num-derive = "0.3.3"
num-traits = "0.2.14"
paste = "1"

[dev-dependencies]
lazy_static = "1"

[badges]
maintenance = { status = "experimental" }
